name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Firebase login
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT_MR_PORTFOLIO_51874 > /tmp/firebase_service_account.json
          firebase login:ci --no-localhost --token "$FIREBASE_TOKEN" < /tmp/firebase_service_account.json
      
      - name: Firebase deploy
        run: firebase deploy --token "$FIREBASE_TOKEN" --project "mr-portfolio-51874"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
